### ISSUE TITLE
When update?

### ISSUE THREAD

**Issue by deniro98** [tbaela/AirSane-openwrt#3]
Hello! Waiting for updates!

**Comment by polikasov** [comment]
Hello, @deniro98!

I don't have OpenWRT router with USB now.
So, I can't test newer versions of AirSane (I'll try with x86_64 OpenWRT)

You can change PKG_SOURCE_VERSION variable to build newer version.
I will create dev branch for untested versions in the future.

**Comment by polikasov** [comment]
Hello, @deniro98!

I don't have OpenWRT router with USB.
So, I can't test newer versions of AirSane (I'll try with x86_64 OpenWRT).

You can change PKG_SOURCE_VERSION variable to build newer version.
